# Generated by Django 4.0.5 on 2022-06-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customchampion',
            name='slug',
        ),
        migrations.AlterField(
            model_name='customchampion',
            name='base_as',
            field=models.FloatField(),
        ),
    ]
