# Generated by Django 4.0.5 on 2022-06-27 06:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customchampion_skill_e_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customchampion',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from=('name', 'title'), unique=True),
            preserve_default=False,
        ),
    ]
