# Generated by Django 4.0.5 on 2022-06-27 07:59

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customchampion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',))),
                ('name', models.CharField(max_length=100)),
                ('lore', models.TextField(blank=True)),
                ('cost', models.IntegerField()),
                ('sell_cost', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customchampion',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('name',)),
        ),
    ]
