# Generated by Django 4.0.5 on 2022-06-27 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customitem_alter_customchampion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customitem',
            name='combine_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
