# Generated by Django 4.0.5 on 2022-06-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_originalitems_customitem_combine_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OriginalItems',
        ),
    ]
