# Generated by Django 4.0.5 on 2022-06-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customitem_stat1_alter_customitem_stat2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customitem',
            name='stat2_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customitem',
            name='stat3_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
