# Generated by Django 4.0.5 on 2022-06-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customitem_active_stat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customitem',
            name='active_stat_unique',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customitem',
            name='passive_stat_unique',
            field=models.BooleanField(default=True),
        ),
    ]
