# Generated by Django 4.0.5 on 2022-06-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customitem_active_stat_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customitem',
            name='active_stat_unique',
            field=models.BooleanField(default=True, help_text='Is Unique?'),
        ),
        migrations.AlterField(
            model_name='customitem',
            name='passive_stat_unique',
            field=models.BooleanField(default=True, help_text='Is Unique?'),
        ),
    ]
