# Generated by Django 4.0.5 on 2022-06-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_customitem_active_stat_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customitem',
            name='stat4',
            field=models.CharField(blank=True, choices=[('Attack Damage', 'Attack Damage'), ('Ability Power', 'Ability Power'), ('Attack Speed', 'Attack Speed'), ('Ability Haste', 'Ability Haste'), ('Critical Chance', 'Critical Chance'), ('Critical Damage', 'Critical Damage'), ('Life Steal', 'Life Steal'), ('Armor Penetration', 'Armor Penetration'), ('Magic Penetration', 'Magic Penetration'), ('Lethality', 'Lethality'), ('Mana', 'Mana'), ('Mana Regen / 5s', 'Mana Regen / 5s'), ('Mana Regen', 'Mana Regen'), ('Health', 'Health'), ('Health Regen / 5s', 'Health Regen / 5s'), ('Health Regen %', 'Health Regen %'), ('Heal and Shield Power', 'Heal and Shield Power'), ('Omni-Vamp', 'Omni-Vamp'), ('Armor', 'Armor'), ('Magic Resist', 'Magic Resist'), ('Movement Speed', 'Movement Speed')], default=0, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customitem',
            name='stat4_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customitem',
            name='type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Basic', 'Basic'), ('Epic', 'Epic'), ('Legendary', 'Legendary'), ('Mythic', 'Mythic'), ('Consumable', 'Consumable')], default='Starter', max_length=100),
            preserve_default=False,
        ),
    ]
