# Generated by Django 4.0.5 on 2022-06-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customitem_stat4_customitem_stat4_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customchampion',
            name='skill_e_icon',
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customchampion',
            name='skill_passive_icon',
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customchampion',
            name='skill_q_icon',
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customchampion',
            name='skill_r_icon',
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customchampion',
            name='skill_w_icon',
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
